extern cvar_t vid_mode, _vid_default_mode_win, scr_uiscale, sensitivityyscale,
_windowed_mouse, newoptions, aspectr, realwidth, realheight, r_draworder,
r_speeds, r_timegraph, r_graphheight, r_clearcolor, r_waterwarp, r_fullbright,
r_drawentities, r_drawviewmodel, r_aliasstats, r_dspeeds, r_drawflat, r_ambient,
r_reportsurfout, r_numsurfs, r_reportedgeout, r_novis, r_particlescale,
r_numedges, r_aliastransbase, r_aliastransadj, r_wateralpha, r_slimealpha,
r_lavaalpha, r_telealpha, r_fogstyle, r_nofog, r_alphastyle, r_dithertex,
r_entalpha, r_labmixpal, r_rgblighting, r_fogbrightness, r_fogfactor, r_lockfog,
r_lockfogd, r_lockfogr, r_lockfogg, r_lockfogb, r_rebuildmips, r_fovmode,
r_fogscale, r_fognoise, r_litwater, vid_cwidth, vid_cheight, vid_cwmode,
r_nolerp_list, r_noshadow_list, r_fullbright_list, bgmvolume, sfxvolume,
precache, loadas8bit, sndspeed, snd_mixspeed, nosound, ambient_level, r_hlwater,
ambient_fade, snd_noextraupdate, snd_show, _snd_mixahead, snd_filterquality,
external_ents, external_vis, external_textures, cl_name, cl_color, cl_shownet,  
cl_nolerp, lookspring, lookstrafe, sensitivity, m_pitch, m_yaw, m_forward,
m_side, cl_maxpitch, cl_minpitch, nomonsters, gamecfg, scratch1, scratch2,
scratch3, scratch4, savedgamecfg, saved1, saved2, saved3, saved4, registered,
cmdline, scr_sidescore, cl_upspeed, cl_forwardspeed, cl_backspeed, cl_sidespeed,
cl_movespeedkey, cl_yawspeed, cl_pitchspeed, cl_anglespeedkey, cl_alwaysrun,
scr_fov, scr_conspeed, scr_centertime, scr_showram, scr_showturtle,
scr_showpause, scr_printspeed, scr_showfps, scr_hudstyle, d_mipcap, d_mipscale,
sv_aim, con_notifytime, r_skyfog, chase_back, chase_up, chase_right,
chase_active, sv_edgefriction, sv_idealpitchscale, sv_altnoclip, sv_maxspeed,
sv_accelerate, scr_screensize, host_framerate, host_speeds, sys_ticrate,
serverprofile, fraglimit, timelimit, teamplay, samelevel, noexit, developer,
skill, deathmatch, coop, pausable, temp1, host_maxfps, host_timescale,
max_edicts, campaign, horde, sv_cheats, sv_friction, sv_stopspeed, sv_gravity,
sv_maxvelocity, sv_nostep, sv_freezenonclients, hostname, scr_viewsize,
scr_ofsx, scr_ofsy, scr_ofsz, cl_rollspeed, cl_rollangle, cl_bob, cl_bobcycle,
cl_bobup, v_kicktime, v_kickroll, v_kickpitch, v_iyaw_cycle, v_iroll_cycle,
v_ipitch_cycle, v_iyaw_level, v_iroll_level, v_ipitch_level, v_idlescale,
crosshair, cl_crossx, cl_crossy, cl_crosschar, gl_cshiftpercent, v_centermove,
v_centerspeed, v_gamma, net_messagetimeout, scr_uixscale, scr_uiyscale,
yaspectscale, jlooksens, jmovesens, jdeadzone, jtriggerthresh, jmoveaxisx,
jmoveaxisy, jlookaxisx, jlookaxisy, jtrigaxis1, jtrigaxis2, jenterbutton,
jescapebutton, joysticknum, scr_lockuiscale, r_enableskybox, r_mipscale,
r_fogdepthcorrection, lyr_main, lyr_sbar, lyr_menu, lyr_centerprint,
lyr_console, lyr_notify, lyr_crosshair, con_logcenterprint, scr_menubgstyle,
r_hlripplescale, r_hlwavescale, r_hlwaterquality, r_particlestyle, cl_nocsqc,
r_particlesize, r_particlealpha, r_renderscale, r_skynoise, pr_checkextension,
scr_sbaralpha, scr_sbarscale, scr_qchudscale, v_saturation, v_contrast,
v_redlevel, v_greenlevel, v_bluelevel, v_hue, v_vibrance, v_brightness;
